In [6]:
#install numpy
!pip install numpy

#import in your script
import numpy as np

#check version
print(np.__version__)

2.0.2


In [7]:
#traditional python list
temps_list=[72,75,68,71,74,69,73]

#convert to numpy array
import numpy as np
temps_array=np.array([72,75,68,71,74,69,73])

print(temps_array)
print(type(temps_array))

[72 75 68 71 74 69 73]
<class 'numpy.ndarray'>


In [13]:
#temperature from 3 sensors over 5 days
sensor_temps=np.array([
  [72,70,71], #day 1
  [75,73,74], #day 2
  [68,67,69], #day 3
  [71,70,72], #day 4
  [74,72,73] #day 5
  ])
print(sensor_temps)
print(f"shape:{sensor_temps.shape}")

[[72 70 71]
 [75 73 74]
 [68 67 69]
 [71 70 72]
 [74 72 73]]
shape:(5, 3)


In [15]:
#array of zeros(5*3)
zeros=np.zeros{(5,3)}

#array of ones(5*3)
ones=np.ones{(5,3)}

#identity matrix(3*3)
identity=np.eye(3)

#range of values
sequence=np.arange(0,10,2)

#evenly spaced values
inspace=np.linspace(0,100,5)

SyntaxError: invalid syntax (ipython-input-1713671237.py, line 2)